import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '../../components/history/Sidebar';
import Providers from '../../components/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Co-Doctor',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
      <body className={`${inter.className} min-h-screen flex`}>
        {/* Sidebar */}
        {/* <div className="w-1/4 bg-slate-300">
          <Sidebar />
        </div> */}

        {/* Main Content */}
        <div className="flex-grow bg-white">
          {children}
        </div>
      </body>
      </Providers>
    </html>
  );
}
